language: node_js
node_js:
- '11'
branchs:
  only:
  - master
cache:
  npm: true
  directories:
  - node_modules
install:
- npm i
script:
- npm run build:prod
before_install:
- openssl aes-256-cbc -K $encrypted_56049a0744f5_key -iv $encrypted_56049a0744f5_iv
  -in id_rsa.enc -out ~\/.ssh/id_rsa -d
after_success:
- sudo chmod 600 ~/.ssh/id_rsa
- ssh  tencent -o StrictHostKeyChecking=no 'cd ~/kede_fe && git pull && npm install
  && npm run build:prod'
